# Generated by Django 6.0.1 on 2026-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
